---
- name: Creates directory
  file:
     path: /etc/issue.d
     state: directory
     owner: root
     group: root
     mode: 0775

- name: Setup /etc/issue.d/splash.issue from template
  template:
     src: splash.issue.j2
     dest: /etc/issue.d/splash.issue
  tags:
     - issue_config
