---
- name: copy neofetch to image
  get_url:
     url: https://raw.githubusercontent.com/dylanaraps/neofetch/master/neofetch
     dest: /usr/local/bin/neofetch
     owner: root
     group: root
     mode: "0755"
  tags:
     - neofetch_get

- name: copy neofetch startup to profile.d
  copy:
     src: neo.sh
     dest: /etc/profile.d/neo.sh
     owner: root
     group: root
     mode: "0755"
  tags:
     - neofetch_startup
