---
# defaults file for flatpak

# Flatpak method: user or system
flatpak_method: system

# Flatpacks repos
flatpak_repos:
  - https://dl.flathub.org/repo/flathub.flatpakrepo

# Packages to install
flatpak_packages:
  - org.gnu.emacs
  - io.neovim.nvim
  - com.visualstudio.code
  - com.slack.Slack
  - com.wps.Office
  - com.skype.Client
  - com.spotify.Client
  - com.obsproject.Studio
  - net.xmind.ZEN
